Advice2.me/Models/Budget.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Advice2.me.Models
{
    public class Budget
    {
        public string name { get; set; }
        public int amount { get; set; }
    }
}

Advice2.me/Models/Messages.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Advice2.me.Models
{
    public class Messages
    {
        public string nameSurname { get; set; }
        public string expertness { get; set; }
        public string lastMessage { get; set; }
        public string lastMessageTime { get; set; }
        public int consultantId { get; set; }
        public string chatId { get; set; }
    }
}

Advice2.me/Models/chats.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advice2.me.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chats
    {
        public int chatId { get; set; }
        public int chatSenderId { get; set; }
        public int chatRecieverId { get; set; }
        public byte[] chatContent { get; set; }
        public System.DateTime chatDate { get; set; }
        public int chatConversationId { get; set; }
    }
}

Advice2.me/Controllers/PanelController.cs
using Advice2.me.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Advice2.me.Controllers
{
    public class PanelController : Controller
    {
        // GET: Panel

        // Sistemdeki aktif danışmanların bilgilerini alıp kullanıcıya sunulmasını sağlayan view'a bilgileri yollayıp, yönlendiren fonksiyon
        public ActionResult Index()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            else
            {
                using (DBModel db = new DBModel())
                {
                    int userId = Convert.ToInt32(Session["userId"]);
                    users User = db.users.Where(x => x.userId == userId).FirstOrDefault();
                    if (User == null)
                        return Redirect("/");
                    else
                    {
                        if (User.userUserType == 1)
                        {
                            List<ConsultantList> constultants = new List<ConsultantList>();
                            var cons = db.consultants.ToList();
                            ViewBag.Bugdet = false;
                            foreach (consultants a in cons)
                            {
                                if (a.consultantPrice != null)
                                {
                                    ConsultantList c = new ConsultantList();
                                    c.consultantId = a.userId;
                                    c.consultantName = a.consultantName + " " + a.consultantSurname;
                                    c.consultantPrice = (int)a.consultantPrice;
                                    var r = db.ratings.Where(x => x.ratingConsultantId == c.consultantId).ToList();
                                    if (r != null)
                                    {
                                        foreach (var t in r)
                                            c.consultantRate += t.ratingAmount;
                                        c.consultantRate /= r.Count;
                                    }
                                    if (a.consultantExpertnessTypeId != null)
                                    {
                                        expertness_types exp = db.expertness_types.Where(x => x.expertnessTypeId == a.consultantExpertnessTypeId).FirstOrDefault();
                                        if(exp != null)
                                            c.consultantExpertness = exp.expertnessTypeName;
                                    }
                                    constultants.Add(c);
                                }
                            }
                            return View(constultants);
                        }
                        else
                            return RedirectToAction("Budget");
                    }
                }
            }
        }

        // Verilen görüşme danışman id'si ve görüşme tipi ile yeni bir görüşme oluşturan fonksiyon
        public ActionResult startNewChat(int consultantId, int type)
        {
            if (Session["userId"] == null)
                return Redirect("/");
            using (DBModel db = new DBModel())
            {
                conversations Con = new conversations();
                Con.conversationAdviseeId = Convert.ToInt32(Session["userId"]);
                Con.conversationConsultantId = consultantId;
                Con.conversationFinishTime = DateTime.Now;
                Con.conversationStartTime = DateTime.Now;
                Con.conversationPayTypeId = 1;
                Con.conversationTypeId = type;
                Con.conversationOver = false;
                db.conversations.Add(Con);
                db.SaveChanges();
                return RedirectToAction("Chat", new { conserId = Con.conversationId.ToString() });
            }
        }

        // Danışmanların bütçelerinin hesaplamalarını yapıp ilgili view'a yollayıp, yönlendiren fonksiyon
        public ActionResult Budget()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            List<Budget> budget = new List<Budget>();
            using (DBModel db = new DBModel())
            {
                int total = 0;
                int userId = Convert.ToInt32(Session["userId"]);
                consultants c = db.consultants.Where(x => x.userId == userId).FirstOrDefault();
                if (c == null)
                    return RedirectToAction("Index");
                var convers = db.conversations.Where(x => x.conversationConsultantId == userId).ToList();
                foreach(var a in convers)
                {
                    if (a.conversationOver)
                    {
                        Budget bud = new Budget();
                        advisees Ads = db.advisees.Where(x => x.userId == a.conversationAdviseeId).FirstOrDefault();
                        bud.name = Ads.adviseeName + " " + Ads.adviseeSurname;
                        if (Ads.adviseeSex == null || (bool)Ads.adviseeSex)
                            bud.name += " Bey";
                        else
                            bud.name += " Hanım";

                        var Chats = db.chats.Where(x => x.chatConversationId == a.conversationId).ToList();
                        if (c.consultantPrice != null)
                        {
                            if (Chats.Count >= 2)
                            {
                                TimeSpan span = Chats.Last().chatDate.Subtract(Chats.First().chatDate);
                                if(span.Hours > 0 || span.Days > 0)
                                    bud.amount = (int)c.consultantPrice * (span.Hours + span.Days * 24);
                                else
                                    bud.amount = (int)c.consultantPrice;
                            }
                            else
                            {
                                bud.amount = (int)c.consultantPrice;
                            }
                            total += bud.amount;
                            budget.Add(bud);
                        }
                    }
                }
                if (c.consultantPrice != null)
                {
                    ViewBag.Total = total;
                }

            }
            return View(budget);
        }

        // Kullanıcının profil bilgilerini profil view'ına yollayıp, yönlendiren fonksiyon
        public ActionResult MyProfile()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            using (DBModel db = new DBModel())
            {
                int userId = Convert.ToInt32(Session["userId"]);
                ViewBag.ExpertnessTypes = db.expertness_types.ToList();
                users User = db.users.Where(x => x.userId == userId).FirstOrDefault();
                if(User.userUserType == 1)
                    ViewBag.Bugdet = false;
                return View(new Profile(userId));
            }
        }
        
        // Verilen form öğeleri doğrultusunda giriş yapmış kullanıcının profil bilgilerini güncelleyen fonksiyon
        public ActionResult ProfileUpdater(FormCollection col)
        {
            if (Session["userId"] == null)
                return Redirect("/");
            int userId = Convert.ToInt32(Session["userId"]);
            Profile profile = new Profile();
            if (profile.newProfile(col, userId))
                TempData["Error"] = "Profiliniz başarıyla güncellendi.";
            else
                TempData["Error"] = "Şifreler birbiriyle eşleşmiyor.";
            return Redirect(Request.UrlReferrer.ToString());
        }

        // Kullanıcıyı contact us view'ına yönlendiren fonksiyon
        public ActionResult ContactUs()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            using (DBModel db = new DBModel())
            {
                int userId = Convert.ToInt32(Session["userId"]);
                users User = db.users.Where(x => x.userId == userId).FirstOrDefault();
                if (User.userUserType == 1)
                    ViewBag.Bugdet = false;
            }
            return View();
        }

        // Kullanıcıyı hakkımızda view'ına yönlendiren fonksiyon
        public ActionResult AboutUs()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            using (DBModel db = new DBModel())
            {
                int userId = Convert.ToInt32(Session["userId"]);
                users User = db.users.Where(x => x.userId == userId).FirstOrDefault();
                if (User.userUserType == 1)
                    ViewBag.Bugdet = false;
            }
            return View();
        }

        // Kullanıcın yaptığı aktif mesajlaşmaları database'den çekip ilgili view'a yollayıp, yönlendiren fonksiyon
        public ActionResult Messages()
        {
            if (Session["userId"] == null)
                return Redirect("/");
            using (DBModel db = new DBModel())
            {
                int userId = Convert.ToInt32(Session["userId"]);
                users User = db.users.Where(x => x.userId == userId).FirstOrDefault();
                if (User.userUserType == 1)
                    ViewBag.Bugdet = false;
            }
            List<Messages> msgs = new List<Messages>();
            using (DBModel db = new DBModel())
            {
                int userID = Convert.ToInt32(Session["userId"]);
                users User = db.users.Where(x => x.userId == userID).FirstOrDefault();
                List<conversations> Conservations = null;
                if (User.userUserType == 1)
                {

Advice2.me/Views/Panel/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<div class="row d-flex justify-content-center ">

    <div class="col-md-5 login-container border-blue">
        <div class="card-body text-align-middle">
            <h5 class="card-title">Biz Kimiz</h5>
            <p class="card-text">Berna TAŞEL 15011049 bernataselbal@gmail.com</p>
            <p class="card-text">Ömer Faruk KAYA 15011084 omerf.kaya97@gmail.com</p>
            <p class="card-text">Emre ÇELİK 15011902 emrecelikk97@gmail.com</p>
        </div>
    </div>
</div>

Advice2.me/Views/Panel/Budget.cshtml
@model IEnumerable<Advice2.me.Models.Budget>
@{
    ViewBag.Title = "Budget";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<main role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-xl-12">
                <span>Toplam Miktar : @ViewBag.Total ₺</span>
            </div>
        </div>
    </div>

    <h2>Hareketler</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Bilgi</th>
                    <th>Miktar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var Budget in Model)
                {
                    <tr>
                        <td>@Budget.name ile görüşme</td>
                        <td>@Budget.amount ₺</td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</main>

Advice2.me/Views/Panel/ContactUs.cshtml
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<div class="row d-flex justify-content-center ">
    <div class="col-md-5 login-container border-blue">
        <div class="card-body text-align-middle">
            @using (Html.BeginForm("ContactUsSend", "Panel", FormMethod.Post))
            {
                if (TempData["Error"] != null)
                {
                    <div class="alert alert-info alert-dismissable">
                        <a class="panel-close close" data-dismiss="alert">×</a>
                        <i class="fa fa-coffee"></i>
                        @TempData["Error"]
                    </div>
                }
                <h5>Bize Ulaşın</h5>
                <div class="form-group">
                    <input type="text" class="form-control" name="nameSurname" required placeholder="İsim Soyisim" value="" />
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="email" required placeholder="Email" value="" />
                </div>
                <div class="form-group">
                    <textarea class="form-control" id="exampleFormControlTextarea1" required name="content" placeholder="Mesaj" rows="4"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Gönder</button>
                </div>
            }
        </div>
    </div>
</div>

Advice2.me/Views/Panel/Index.cshtml
@model IEnumerable<Advice2.me.Models.ConsultantList>
@{
    ViewBag.Title = "Danışmanları/Psikologları Listele";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<!--nav class="navbar navbar-light bg-light justify-content-between">
    <a class="navbar-brand">Puanına Göre</a>
    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Ara" aria-label="Search">
        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Ara</button>
    </form>
</nav-->
<div style="margin:20px;">
    <table id="myTable" class="table table-striped">
        <thead>
            <tr>
                <th>Resim</th>
                <th>Adı Soyadı</th>
                <th>Uzmanlık Alanı</th>
                <th>Fiyatı ₺</th>
                <th>Puanı</th>
                <th>Görüşmeyi Başlat</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
            <tr>
                <td><img class="bd-placeholder-img card-img-top" src="/Panel/Show?userId=@user.consultantId" style="width:100px" ></td>
                <td style="line-height:90px">@user.consultantName</td>
                <td style="line-height:90px">@user.consultantExpertness</td>
                <td style="line-height:90px">@user.consultantPrice</td>
                <td style="line-height:90px">@user.consultantRate</td>
                <td style="text-align:center;">
                    <div id="btnwrap">
                        <button type="button" class="btn btn-sm btn-warning tableButton toChat" userId="@user.consultantId" style="width:100%; height:100px">Görüşmeyi başlat</button>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Mesajlaşmaya Başlamadan Önce..</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bilgilerinizi Danışmanın Görmesini Onaylıyor Musunuz ?
            </div>
            <div class="modal-footer">
                <button type="button" id="startW" class="btn btn-primary">Onayla</button>
                <button type="button" id="startWO" class="btn btn-light">Onaylama</button>
            </div>
        </div>
    </div>
</div>

<script>
    var consultantId = 0;
    $(".album").css("height", $(window).height() - 130);
    $(".toChat").click(function () {
        consultantId = this.getAttribute("userId");
        $("#exampleModal").modal('show');
    });
    $("#startWO").click(function () {
        document.location = "/Panel/startNewChat?consultantId=" + consultantId + "&type=2";
    });
    $("#startW").click(function () {
        document.location = "/Panel/startNewChat?consultantId=" + consultantId + "&type=1";
    });
</script>

Advice2.me/Views/Panel/Messages.cshtml
@model IEnumerable<Advice2.me.Models.Messages>
@{
    ViewBag.Title = "Messages";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<div class="max-width">
    @foreach (Advice2.me.Models.Messages msg in Model)
    {
        <a href="/panel/chat?conserId=@msg.chatId" class="max-width person-msg" style="text-decoration:none; height: 20%">
            <img class="profile" src="/Panel/Show?userId=@msg.consultantId" alt="Simply Easy Learning" width="100" height="100" style="float:left;">
            <p class="NameSurnameCSS">@msg.nameSurname</p>
            <p class="DateCSS">@msg.lastMessageTime</p>
            <p class="TitleCSS">@msg.expertness</p>

            <p class="LastMessageCSS">@msg.lastMessage</p>
            <hr>
        </a>
    }
</div>

Advice2.me/Views/Panel/MyProfile.cshtml
@model Advice2.me.Models.Profile
@{
    ViewBag.Title = "MyProfile";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
    List<Advice2.me.Models.expertness_types> expertness_Types = (List<Advice2.me.Models.expertness_types>)ViewBag.ExpertnessTypes;
}

<div class="container">
    <h1>Profili Düzenle</h1>
    <hr>
    <div class="row">
        <!-- Sol Taraf -->
        <div class="col-md-3">
            <div class="text-center avatarArea">
                <div class="alert alert-info alert-dismissable resimOK" style="display:none">
                    <i class="fa fa-coffee"></i>
                    Fotoğraf başarı ile güncellendi.
                </div>
                <img src="/Panel/Show?userId=@Session["userId"]" class="avatar img-circle" alt="avatar" />
                <h7 class="changePhoto">Yeni Resim Yükle</h7>
            </div>
            <input type="file" id="imageUploadForm" name="image" style="display:none;"/>
        </div>

        <!-- Alert Mesajı -->
        <div class="col-md-9 personal-info">
            @if (TempData["Error"] != null)
            {
                <div class="alert alert-info alert-dismissable">
                    <a class="panel-close close" data-dismiss="alert">×</a>
                    <i class="fa fa-coffee"></i>
                    @TempData["Error"]
                </div>
            }
            @using (Html.BeginForm("ProfileUpdater", "Panel", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <h3>Kişisel Bilgiler</h3>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Ad:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="name" value="@Model.name" >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Soyad:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="surname" value="@Model.surname" >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">TC:</label>
                    <div class="col-lg-8">
                        <input class="form-control" name="TC" id="TC" value="@Model.TC" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Doğum Tarihi:</label>
                    <div class="col-lg-8">
                        <input class="form-control" name="bornDate" value="@Model.bornDate" type="date">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Cinsiyet:</label>
                    <div class="col-lg-8">
                        <div class="ui-select">
                            <select id="user_time_zone" name="sex" class="form-control">
                                @if (Model.sex == true)
                                {
                                    <option value="1" selected>Erkek</option>
                                    <option value="0">Kadın</option>
                                }
                                @if ((Model.sex) == false)
                                {
                                    <option value="1">Erkek</option>
                                    <option value="0" selected>Kadın</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Şifre:</label>
                    <div class="col-md-8">
                        <input class="form-control" name="password" type="password" value="@Model.password">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Şifreyi Tekrarlayın:</label>
                    <div class="col-md-8">
                        <input class="form-control" name="rePassword" type="password" value="@Model.password">
                    </div>
                </div>
                <h3>İletişim Bilgileri</h3>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Email:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="email" value="@Model.email" >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Cep Telefonu:</label>
                    <div class="col-lg-8">
                        <input class="form-control" type="text" name="phone" value="@Model.phone" placeholder="05xx xxx xx xx">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Adres:</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" id="inputAddress" name="adress" value="@Model.address" placeholder="Davutpaşa Mah. Esenler / İstanbul">
                    </div>
                </div>
                if (Model.userType == 2)
                {
                    <h3>Uzmanlık Bilgileri</h3>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Diploma No:</label>
                        <div class="col-lg-8">
                            <input class="form-control" name="diplomaNo" value="@Model.diplomaNo" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Mezun Olunan Okul:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="school" value="@Model.school">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Mezun Olunan Bölüm:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="department" value="@Model.department">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Uzmanlık Alanları:</label>
                        <div class="col-lg-8">
                            <select id="user_time_zone" class="form-control" name="expertnessTypeId">
                                @foreach (var type in expertness_Types)
                                {
                                    if (Model.expertnessType == type.expertnessTypeId)
                                    {
                                        <option value="@type.expertnessTypeId" selected>@type.expertnessTypeName</option>
                                    }
                                    else
                                    {
                                        <option value="@type.expertnessTypeId">@type.expertnessTypeName</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                    <h3>Banka Bilgisi</h3>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">IBAN:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" name="IBAN" value="@Model.IBAN">
                        </div>
                    </div>
                    <h3>Ücret Bilgisi</h3>
                    <div class="form-group">
                        <label class="col-lg-3 control-label">Seans Ücreti:</label>
                        <div class="col-lg-8">
                            <input class="form-control" type="text" id="price" name="price" value="@Model.price">
                        </div>
                    </div>
                }
                <div class="form-group" style="padding-bottom: 70px">
                    <div class="col-md-8">
                        <input type="submit" style="transform: unset" class="btn btn-primary" value="Kaydet">
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>

    // Resmin üzerine tıklandığında resim yükleme ekranının açılmasını sağlar
    $(".avatarArea").click(function () {
        $("input[id='imageUploadForm']").click();
    });
    // Seçilen resmin database'e yüklenmesini sağlar
    $(document).ready(function () {
        $("#imageUploadForm").change(function () {
            var formData = new FormData();
            var totalFiles = document.getElementById("imageUploadForm").files.length;
            for (var i = 0; i < totalFiles; i++) {
                var file = document.getElementById("imageUploadForm").files[i];
                formData.append("imageUploadForm", file);
            }
            $.ajax({
                type: "POST",
                url: '/Panel/PictureUpdate',
                data: formData,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function () { $(".resimOK").css("display", "block"); }
            });
        });
    });

    // Input alanlarına filtre uygulanmasını sağlayan fonksiyon.
    function setInputFilter(textbox, inputFilter) {
        ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function (event) {
            textbox.addEventListener(event, function () {
                if (inputFilter(this.value)) {
                    this.oldValue = this.value;
                    this.oldSelectionStart = this.selectionStart;
                    this.oldSelectionEnd = this.selectionEnd;
                } else if (this.hasOwnProperty("oldValue")) {
                    this.value = this.oldValue;
                    this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
                }
            });
        });
    }


    // idsi tc olan input alanının numeric olmasını ve 11 haneden küçük ve eşit olmasını sağlayan fonksiyon.
    setInputFilter(document.getElementById("TC"), function (value) {
        return /^\d*$/.test(value) && (value === "" || parseInt(value) <= 99999999999);
    });
    // idsi price olan input alanının numeric ve 0dan büyük olmasını sağlayan fonksiyon.

    setInputFilter(document.getElementById("price"), function (value) {
        return /^\d*$/.test(value) && (value === "" || parseInt(value) > 0);
    });
    // type ı date olan input alanına tarih formatında veri girilmesini sağlar.
    jQuery('input[type="date"]')
        .each(function () {
            Object.defineProperty(this, 'value', {
                get: function () {
                    return myFormatDateFunction(this.valueAsDate, 'dd.mm.yyyy');
                },
                configurable: true,
                enumerable: true
            });
        });  
</script>